export const navbarLayout = {
	rail: "relative z-40 flex h-full w-16 min-w-16 max-w-16 shrink-0 flex-col items-center overflow-visible border-r border-white/10 bg-[#0b1016]/95 px-2 py-3 backdrop-blur-xl",
	railMark: "grid h-11 w-11 shrink-0 place-items-center",
	railNav: "flex min-h-0 w-full flex-1 flex-col items-center pt-3",
	railRoutes: "command-rail-scroll flex min-h-0 w-full flex-1 flex-col items-center gap-1 overflow-y-auto overflow-x-hidden",
	railBottom: "flex shrink-0 flex-col items-center border-t border-white/10 pt-3",
	railStatus: "mt-2 shrink-0",
	railButton: "group navbar-motion relative grid h-11 w-11 shrink-0 place-items-center rounded-xl text-base outline-none transition-[color,background-color,box-shadow] duration-200 focus-visible:ring-2 focus-visible:ring-cyan-400 active:bg-white/10",
	railButtonActive: "bg-[#ff4655] text-white shadow-lg shadow-[#ff4655]/20",
	railButtonInactive: "text-gray-500 hover:bg-white/5 hover:text-white",
	railSelectionMarker: "absolute left-0 h-5 w-0.5 rounded-r-full bg-white/85 shadow-[0_0_10px_rgba(255,255,255,0.45)]",
	railIcon: "grid h-5 w-5 place-items-center",
	tooltip: "navbar-motion pointer-events-none fixed z-[60] -translate-y-1/2 whitespace-nowrap rounded-md border border-white/10 bg-[#111820] px-2.5 py-1.5 text-xs font-medium text-white shadow-xl transition-[opacity,transform] duration-150",
	tooltipVisible: "translate-x-0 opacity-100",
	tooltipHidden: "translate-x-1 opacity-0",
	statusTooltip: "navbar-motion pointer-events-none absolute left-full top-1/2 z-[60] ml-3 -translate-y-1/2 translate-x-1 whitespace-nowrap rounded-md border border-white/10 bg-[#111820] px-2.5 py-1.5 text-xs font-medium text-white opacity-0 shadow-xl transition-[opacity,transform] duration-150 group-hover:translate-x-0 group-hover:opacity-100 group-focus-visible:translate-x-0 group-focus-visible:opacity-100",
	statusTrigger: "flex h-10 max-w-56 items-center gap-2 rounded-md border border-transparent px-2 text-sm text-gray-300 transition-colors hover:border-white/10 hover:bg-white/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400",
	statusTriggerCompact: "group navbar-motion relative grid h-11 w-11 place-items-center rounded-xl border border-transparent text-gray-500 outline-none transition-[color,background-color,border-color] duration-200 hover:border-white/10 hover:bg-white/5 hover:text-white focus-visible:ring-2 focus-visible:ring-cyan-400",
	statusMenu: "absolute right-0 top-11 z-50 w-60 max-w-[calc(100vw-1rem)] rounded-lg border border-white/10 bg-[#111318] p-1.5 shadow-2xl",
	statusMenuCompact: "absolute bottom-0 left-full z-50 ml-3 w-60 max-w-[calc(100vw-5rem)] rounded-lg border border-white/10 bg-[#111318] p-1.5 shadow-2xl",
	statusMessage: "mt-1 whitespace-normal break-words border-t border-white/10 px-2.5 pt-2 text-[11px] leading-4",
} as const;
