export const navbarLayout = {
	root: "relative z-40 shrink-0 border-b border-white/10 bg-[#0b1016]/95 backdrop-blur-xl",
	utilityRow: "flex h-12 items-center justify-between gap-4 px-4",
	wordmark: "flex items-center gap-2 font-[Rajdhani] text-sm font-bold tracking-[0.16em] text-white",
	wordmarkBadge: "grid h-7 w-7 place-items-center bg-[#ff4655] text-xs font-extrabold text-white [clip-path:polygon(0_0,100%_0,86%_78%,50%_100%,14%_78%)]",
	dockViewport: "nav-tabs-scroll overflow-x-auto px-4 pb-3",
	dock: "relative mx-auto flex w-max min-w-max items-center gap-1 rounded-xl border border-white/10 bg-[#18222b] p-1 shadow-xl shadow-black/25",
	dockTab: "navbar-motion flex h-11 items-center gap-2 rounded-lg px-3 text-sm font-medium outline-none transition-[color,background-color,box-shadow] duration-200 focus-visible:ring-2 focus-visible:ring-cyan-400 active:bg-white/10",
	dockTabActive: "bg-[#ff4655] text-white shadow-lg shadow-[#ff4655]/20",
	dockTabInactive: "text-gray-400 hover:bg-white/5 hover:text-white",
	status: "relative shrink-0 flex items-center",
	overflowMenu: "absolute right-0 top-full z-50 mt-2 w-48 rounded-lg border border-white/10 bg-[#111820] p-1.5 shadow-2xl",
	overflowItem: "flex min-h-10 w-full items-center gap-2 rounded-md px-3 text-left text-sm text-gray-300 outline-none hover:bg-white/5 focus-visible:ring-2 focus-visible:ring-cyan-400",
	overflowItemActive: "bg-white/8 text-white",
	statusMenu: "absolute right-0 top-11 z-50 w-60 max-w-[calc(100vw-1rem)] rounded-lg border border-white/10 bg-[#111318] p-1.5 shadow-2xl",
	statusMessage: "mt-1 whitespace-normal break-words border-t border-white/10 px-2.5 pt-2 text-[11px] leading-4",
} as const;
