export const navbarLayout = {
	root: "relative z-40 shrink-0 border-b border-white/10 bg-[#0b1016]/95 backdrop-blur-xl",
	utilityRow: "flex h-12 items-center justify-between gap-4 px-4",
	wordmark: "flex items-center gap-2 font-[Rajdhani] text-sm font-bold tracking-[0.16em] text-white",
	wordmarkBadge: "grid h-7 w-7 place-items-center bg-[#ff4655] text-xs font-extrabold text-white [clip-path:polygon(0_0,100%_0,86%_78%,50%_100%,14%_78%)]",
	dockViewport: "nav-tabs-scroll overflow-x-auto px-4 pb-3",
	dock: "relative mx-auto flex w-max min-w-max items-center gap-1 rounded-xl border border-white/10 bg-[#18222b] p-1 shadow-xl shadow-black/25",
	dockTab: "navbar-motion flex h-11 items-center gap-2 rounded-lg px-3 text-sm font-medium outline-none transition-[color,background-color,box-shadow] duration-200 focus-visible:ring-2 focus-visible:ring-cyan-400 active:bg-white/10",
	dockTabActive: "bg-[#ff4655] text-white shadow-lg shadow-[#ff4655]/20",
	dockTabInactive: "text-gray-400 hover:bg-white/5 hover:text-white",
	status: "relative shrink-0 flex items-center",
	rail: "relative z-40 flex h-full w-16 min-w-16 max-w-16 shrink-0 flex-col items-center overflow-visible border-r border-white/10 bg-[#0b1016]/95 px-2 py-3 backdrop-blur-xl",
	railMark: "grid h-10 w-10 shrink-0 place-items-center bg-[#ff4655] font-[Rajdhani] text-sm font-extrabold text-white shadow-lg shadow-[#ff4655]/20 [clip-path:polygon(0_0,100%_0,86%_78%,50%_100%,14%_78%)]",
	railNav: "flex min-h-0 flex-1 flex-col items-center gap-1 pt-4",
	railBottom: "flex shrink-0 flex-col items-center gap-2 border-t border-white/10 pt-3",
	railButton: "group navbar-motion relative grid h-11 w-11 shrink-0 place-items-center rounded-xl text-base outline-none transition-[color,background-color,box-shadow] duration-200 focus-visible:ring-2 focus-visible:ring-cyan-400 active:bg-white/10",
	railButtonActive: "bg-[#ff4655] text-white shadow-lg shadow-[#ff4655]/20",
	railButtonInactive: "text-gray-500 hover:bg-white/5 hover:text-white",
	railSelectionMarker: "absolute -left-2 h-5 w-0.5 rounded-r-full bg-[#ff4655] shadow-[0_0_10px_rgba(255,70,85,0.75)]",
	railIcon: "grid h-5 w-5 place-items-center",
	tooltip: "pointer-events-none absolute left-full top-1/2 z-[60] ml-3 -translate-y-1/2 translate-x-1 whitespace-nowrap rounded-md border border-white/10 bg-[#111820] px-2.5 py-1.5 text-xs font-medium text-white opacity-0 shadow-xl transition-[opacity,transform] duration-150 group-hover:translate-x-0 group-hover:opacity-100 group-focus-visible:translate-x-0 group-focus-visible:opacity-100",
	overflowMenu: "fixed z-50 max-h-48 w-48 overflow-y-auto rounded-lg border border-white/10 bg-[#111820] p-1.5 shadow-2xl",
	overflowItem: "flex min-h-10 w-full items-center gap-2 rounded-md px-3 text-left text-sm text-gray-300 outline-none hover:bg-white/5 focus-visible:ring-2 focus-visible:ring-cyan-400",
	overflowItemActive: "bg-white/8 text-white",
	statusMenu: "absolute right-0 top-11 z-50 w-60 max-w-[calc(100vw-1rem)] rounded-lg border border-white/10 bg-[#111318] p-1.5 shadow-2xl",
	statusMessage: "mt-1 whitespace-normal break-words border-t border-white/10 px-2.5 pt-2 text-[11px] leading-4",
} as const;
