//! Shared test-only helpers for comparing this crate's JSON output against
//! the golden fixtures in `test-fixtures/golden/`. Used by both
//! `extract.rs`'s and `abilities.rs`'s `#[cfg(test)]` modules.

#![cfg(test)]

use std::path::{Path, PathBuf};

use serde_json::Value;

/// Read a real `.vrf` fixture shared with the TS package (same fixtures
/// `valorant::replay_reader`'s own tests use).
pub fn fixture_bytes(name: &str) -> Vec<u8> {
    let path = format!(
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../package/ts-replay-parser/src/valorant/__fixtures__/{}"
        ),
        name
    );
    std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read fixture {path}: {e}"))
}

/// Directory holding a fixture's golden `positions.json`/`events.json`/
/// `meta.json`/`abilities.json`/`channels.jsonl` (generated by actually
/// running the TS sidecar).
pub fn golden_dir(uuid: &str) -> PathBuf {
    PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/test-fixtures/golden")).join(uuid)
}

pub fn read_json(path: &Path) -> Value {
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {} as JSON: {e}", path.display()))
}

/// Deep-equality assertion between two JSON values that:
/// - ignores any object key named `generatedAt` (wall-clock-dependent in
///   both the TS source and this port)
/// - compares numbers by parsed `f64` value rather than by underlying
///   textual representation, since this crate's `serde_json` dependency
///   uses the `arbitrary_precision` feature (numbers keep their original
///   formatting instead of being normalized), and Rust's `f64` `Display`
///   vs. JS's `toFixed`-derived number text can legitimately differ in
///   representation (e.g. trailing zeros) while denoting the identical
///   value
pub fn assert_json_eq(actual: &Value, expected: &Value, path: &str) {
    match (actual, expected) {
        (Value::Number(a), Value::Number(b)) => {
            let (af, bf) = (a.as_f64().unwrap(), b.as_f64().unwrap());
            assert!(
                (af - bf).abs() < 1e-9,
                "numeric mismatch at {path}: actual={af} expected={bf}"
            );
        }
        (Value::String(a), Value::String(b)) => {
            assert_eq!(a, b, "string mismatch at {path}");
        }
        (Value::Bool(a), Value::Bool(b)) => {
            assert_eq!(a, b, "bool mismatch at {path}");
        }
        (Value::Null, Value::Null) => {}
        (Value::Array(a), Value::Array(b)) => {
            assert_eq!(
                a.len(),
                b.len(),
                "array length mismatch at {path}: actual={a:?} expected={b:?}"
            );
            for (i, (av, bv)) in a.iter().zip(b.iter()).enumerate() {
                assert_json_eq(av, bv, &format!("{path}[{i}]"));
            }
        }
        (Value::Object(a), Value::Object(b)) => {
            let mut a_keys: Vec<&String> = a.keys().filter(|k| *k != "generatedAt").collect();
            let mut b_keys: Vec<&String> = b.keys().filter(|k| *k != "generatedAt").collect();
            a_keys.sort();
            b_keys.sort();
            assert_eq!(a_keys, b_keys, "object key set mismatch at {path}");
            for k in a_keys {
                assert_json_eq(&a[k], &b[k], &format!("{path}.{k}"));
            }
        }
        (a, b) => panic!("type mismatch at {path}: actual={a:?} expected={b:?}"),
    }
}
